navigation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _

from portal import views as portal_views

admin.site.site_header = _('Portal Management')
admin.site.index_title = _('Site Admin')
admin.site.site_title = _('Portal')

# ================================ URL ================================
urlpatterns = [
    #################################### index
    #
    url(r'^$', portal_views.show_index, name='index'),
    #################################### apps
    #
    url(r'^portal/', include('portal.urls')),
    #################################### admin
    #
    url(r'^admin/', include(admin.site.urls)),
    #################################### i18n
    #
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.conf.urls import url
from . import views

app_name = 'portal'
urlpatterns = [
    #################################### /portal/xxx
    #
    url(r'^$', views.show_index, name='show_index'),
    url(r'^help$', views.show_help, name='show_help'),
    url(r'^show/app/(?P<app_id>[0-9]+)$', views.show_app, name='show_app'),
    url(r'^show/app/default$', views.show_app_default, name='show_app_default'),
    url(r'^show/tree$', views.show_tree, name='show_tree'),
    url(r'^show/nav$', views.show_nav, name='show_nav'),
    #################################### /portal/set/xxx
    #
    url(r'^set/default$', views.set_default_app_cat_and_link, name='set_default_app_cat_and_link'),
]

portal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from django.db import models

from .apps import CHOICES_ICONS

# Create your models here.


@python_2_unicode_compatible
class Level1BizGroup(models.Model):
    bg_id = models.IntegerField(_('id'), unique=True, default=1)
    bg_name = models.CharField(_('name'), max_length=50, unique=True, default='DEFAULT')
    bg_rank = models.IntegerField(_('rank'), default=0)

    def __str__(self):
        return self.bg_name

    class Meta:
        verbose_name = _('biz group')
        verbose_name_plural = _('biz group')


@python_2_unicode_compatible
class Level2WorkGroup(models.Model):
    wg_id = models.IntegerField(_('id'), unique=True, default=1)
    wg_name = models.CharField(_('name'), max_length=50, unique=True, default='DEFAULT')
    wg_rank = models.IntegerField(_('rank'), default=0)
    added_to_navbar = models.BooleanField(_('added to navbar?'), default=False)
    bg = models.ForeignKey(Level1BizGroup, default='1', on_delete=models.CASCADE, verbose_name=_('biz group'))

    def __str__(self):
        return self.wg_name

    class Meta:
        verbose_name = _('work group')
        verbose_name_plural = _('work group')


@python_2_unicode_compatible
class Level3App(models.Model):
    app_id = models.IntegerField(_('id'), unique=True, default=1)
    app_name = models.CharField(_('name'), max_length=50, unique=True, default='DEFAULT')
    app_ename = models.CharField(_('en name'), max_length=50, unique=True, default='DEFAULT')
    is_enabled = models.BooleanField(_('is enabled?'), default=False)
    app_rank = models.IntegerField(_('rank'), default=0)
    wg = models.ForeignKey(Level2WorkGroup, default='1', on_delete=models.CASCADE, verbose_name=_('work group'))

    def __str__(self):
        return self.app_name

    class Meta:
        verbose_name = _('app')
        verbose_name_plural = _('app')


@python_2_unicode_compatible
class Level4AppCategory(models.Model):
    cat_name = models.CharField(_('name'), max_length=50, unique=True, default='DEFAULT')
    cat_rank = models.IntegerField(_('rank'), default=0)
    app = models.ForeignKey(Level3App, default='1', on_delete=models.CASCADE, verbose_name=_('app'))

    def __str__(self):
        return self.cat_name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('category')


@python_2_unicode_compatible
class Level5AppLink(models.Model):
    link_name = models.CharField(_('name'), max_length=50, unique=True, default='DEFAULT')
    link_href = models.CharField(_('href'), max_length=500, default='#')
    link_img = models.CharField(_('icon'), max_length=50, choices=CHOICES_ICONS, default='icons/default.svg')
    link_img_upload = models.ImageField(_('custom icon'), upload_to='icons', default='', blank=True)
    cat = models.ForeignKey(Level4AppCategory, default='1', on_delete=models.CASCADE, verbose_name=_('category'))

    def __str__(self):
        return self.link_name

    class Meta:
        verbose_name = _('link')
        verbose_name_plural = _('link')

portal/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.shortcuts import render
from django.http import JsonResponse

from .models import Level1BizGroup, Level2WorkGroup, Level3App, Level4AppCategory, Level5AppLink


# Create your views here.

# ================================ /portal/index ================================
def show_index(request):
    """
    show index.
    """
    return render(request, 'portal/index.html')


def show_help(request):
    """
    show help.
    """
    return render(request, 'portal/help.html')


# ================================ /portal/app/id ================================
def show_app_default(request):
    """
    return json data for content right as default info.
    """
    default_content = {
        'title': _('Portal'),
        "data": []
    }
    return JsonResponse(default_content)


def get_links_by_id(id):
    """
    return json data in list for links filtered by id.
    """
    links = Level5AppLink.objects.filter(cat_id=id).order_by('link_name')
    tree_view_level5_nodes = []
    for n in links:
        node = {
            'name': n.link_name,
            'href': n.link_href,
            'img': '/media/{0}'.format(n.link_img if n.link_img_upload == '' else n.link_img_upload)
        }
        tree_view_level5_nodes.append(node)

    return tree_view_level5_nodes


def show_app(request, app_id):
    """
    return json data for app filtered by id.
    require: get_links_by_id.
    """
    this_app = Level3App.objects.get(app_id=app_id).app_name
    app_cat = Level4AppCategory.objects.filter(app__app_id=app_id).order_by('cat_rank')
    tree_view_level4_nodes = {
        'title': this_app,
        "data": []
    }
    for n in app_cat:
        tree_view_level4_nodes["data"].append({
            'id': this_app,
            'name': n.cat_name,
            'links': get_links_by_id(n.id)
        })

    return JsonResponse(tree_view_level4_nodes)


# ================================ /portal/show/tree ================================
def get_apps_by_id(id):
    """
    return json data in list for apps filtered by id.
    """
    work_groups = Level3App.objects.filter(wg__wg_id=id).filter(is_enabled=True).order_by('app_rank')
    tree_view_level3_nodes = []
    for n in work_groups:
        node = {
            'text': n.app_name,
            'href': '#appid_{0}'.format(n.app_id),
        }
        tree_view_level3_nodes.append(node)

    return tree_view_level3_nodes


def get_work_groups_by_id(id):
    """
    return json data in list for work groups filtered by id.
    """
    work_groups = Level2WorkGroup.objects.filter(bg__bg_id=id).order_by('wg_rank')
    tree_view_level2_nodes = []
    for n in work_groups:
        node = {
            'text': n.wg_name,
            'href': '#',
            'nodes': get_apps_by_id(n.wg_id)
        }
        if len(node['nodes']) == 0:
            continue
        tree_view_level2_nodes.append(node)

    return tree_view_level2_nodes


def show_tree(request):
    """
    return json data for treeview.
    require: get_work_groups_by_id, get_apps_by_id.
    """
    biz_groups = Level1BizGroup.objects.order_by('bg_rank')
    tree_view_level1_nodes = {
        'comment': "",
        "data": []
    }
    for n in biz_groups:
        node = {
            'text': n.bg_name,
            'href': '#',
            'nodes': get_work_groups_by_id(n.bg_id)
        }
        if len(node['nodes']) == 0:
            continue
        tree_view_level1_nodes['data'].append(node)

    return JsonResponse(tree_view_level1_nodes)


# ================================ /portal/show/navbar ================================
def show_nav(request):
    """
    return json data for navbar.
    require: get_apps_by_id.
    """
    biz_groups = Level1BizGroup.objects.order_by('bg_rank')
    nav_bar_level1_nodes = {
        'comment': "",
        "data": []
    }
    for b in biz_groups:
        work_groups = Level2WorkGroup.objects.filter(bg__bg_id=b.bg_id).filter(added_to_navbar=True).order_by('wg_rank')
        for n in work_groups:
            node = {
                'text': n.wg_name,
                'href': '#',
                'nodes': get_apps_by_id(n.wg_id)
            }
            if len(node['nodes']) == 0:
                continue
            nav_bar_level1_nodes['data'].append(node)

    return JsonResponse(nav_bar_level1_nodes)


# ================================ set default data for exp ================================
def set_default_app_cat_and_link(request):
    """
    set default link for each app.
    """
    apps = Level3App.objects.filter(is_enabled=True).order_by('app_name')

    context = {}
    for app in apps:
        count_error = 0
        try:
            (cat, status) = Level4AppCategory.objects.get_or_create(
                    cat_name='default({0})'.format(app.app_name),
                    app=app
            )
            #print('cat={0}, status={1}'.format(cat.cat_name, status))
            context['cat={0}'.format(cat.cat_name)] = 'status={0}'.format(status)

            href = 'http://nav.test.com/test?app={0}_{1}'.format(app.app_ename, app.app_id)
            (link, status) = Level5AppLink.objects.get_or_create(
                    link_name='default({0})'.format(app.app_name),
                    link_href=href,
                    cat=cat
            )
            #print('link={0}, status={1}'.format(link.link_name, status))
            context['link={0}'.format(link.link_name)] = 'status={0}'.format(status)

        except Exception as e:
            print('[error]: {0}'.format(e))
            count_error += 1
            continue
        print('[count_error]: {0}'.format(count_error))
        context['count_error'] = count_error

    return JsonResponse(context)

portal/templates/portal/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    <title>{% block titles %} base template {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'portal/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'portal/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- 自定义的 css -->
    {% block css4this %}{% endblock %}
</head>
<body>
    <!-- 【顶部菜单】-->
    {% block navbar %}{% endblock %}
    <!-- 【正文】-->
    <div class="container-fluid">
        <div class="row">
            <!-- 【左侧内容】-->
            {% block content_left %}{% endblock %}

            <!-- 【右侧内容】-->
            {% block content_right %}{% endblock %}
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'portal/js/jquery-2.2.0.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'portal/js/jquery-2.2.0.min.js' %}"><\/script>')</script>
    <script src="{% static 'portal/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'portal/js/bootstrap-treeview.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'portal/js/ie10-viewport-bug-workaround.js' %}"></script>

    <!-- 自定义的 js -->
    {% block js4this %}{% endblock %}
</body>
</html>

portal/templates/portal/help.html
{% extends 'portal/base.html' %}
{% load i18n static %}
{% block titles %}{% trans 'Help' %}{% endblock %}
{% block content_right %}
            <div class="col-md-8 col-md-offset-2">
                <h2>{% trans 'Help' %}</h2>
                <a class="btn" href="{% static 'portal/images/logo.png' %}">
                    <img src="{% static 'portal/images/logo.png' %}" class="img-thumbnail">
                </a>
            </div>
{% endblock %}

portal/templates/portal/index.html
{% extends 'portal/base.html' %}
{% load i18n static %}
{% block titles %}{% trans 'Portal' %}{% endblock %}
{% block css4this %}
    <link href="{% static 'portal/css/main.css' %}" rel="stylesheet">
{% endblock %}
{% block navbar %}
    {% include "portal/nav.html" %}
{% endblock %}
{% block content_left %}
            <div class="col-md-3 sidebar">
                <div id="tree"></div>
            </div>
{% endblock %}
{% block content_right %}
            <div class="col-md-9 col-md-offset-3 main">
                <h2 id="sub_header" class="sub-header">{% trans 'Portal' %}</h2>
                <!-- Primary panel Start-->
                <div id="panel_lists" class="panel-group panel-group-primary">
                <!-- 【下面是一段示例代码，页面加载时将使用 main.js 来自动生成下面的 html code】-->
                    <!-- panel Start-->
                    <!--
                    <div class="panel" id="links_online">
                        <div class="panel-heading">
                            <span class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#links_online" href="#collapse_A1">
                                    <strong id="this_title" class="label label-success label-tag">title1</strong>
                                </a>
                            </span>
                        </div>
                        <div id="collapse_A1" class="panel-collapse in">
                            <div class="panel-body placeholders">
                                <div class="col-xs-4 col-sm-2 placeholder">
                                    <a class="Portal" target="_blank" href="#">
                                        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" class="img-item-list img-responsive">
                                        <h5 class="text-muted">Portal</h5>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    -->
                    <!-- End of panel-->

                </div>
                <!-- End of Primary panel -->
            </div>
{% endblock %}
{% block js4this %}
    <script src="{% static 'portal/js/main.js' %}"></script>
{% endblock %}

portal/templates/portal/nav.html
{% load i18n static %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img class="img-rounded img-logo" src="{% static 'portal/images/logo.png' %}" />
                </a>
                <a class="navbar-brand" href="/">
                    test.com
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
            <!-- 【顶部菜单-左侧】-->
                <ul id="navbar_top" class="nav navbar-nav navbar-left">
                </ul>
            <!-- 【顶部菜单-右侧】 -->
                <!-- 【i18n】 -->
                <form class="navbar-right navbar-form" role="setlang" id="form-language" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <select name="language" class="form-control">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <button type="submit"  class="btn btn-default">{% trans 'GO' %}</button>
                </form>

                <!-- 【user】 -->
                <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {% trans 'Signed in as: ' %}{{ user.username }}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'admin:index' %}" class="navbar-link">
                                {% trans 'Management' %}
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="/admin/logout" class="navbar-link">
                                {% trans 'Sign out' %}
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a href="/admin" class="navbar-link">
                            {% trans 'Sign in' %}
                        </a>
                    </li>
                {% endif %}
                    <li>
                        <a href="{% url 'portal:show_help' %}" class="navbar-link" target="_blank">
                            {% trans 'Help' %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>